=== automotiveteamleader/Flashbootloader_RH850_GM/Misc/HdrGen/GmHeader.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2009 sp1 (http://www.altova.com) by Vector Employee (Vector Informatik GmbH) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<!-- XML Schema 2016-08-12 Awh-->
	<!-- with XmlGrid.net Free Online Service http://xmlgrid.net -->
	<xs:element name="GmProject">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="HeaderVersion" type="xs:double"/>
				<xs:element name="SignedHeaderInfo">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="image" type="xs:string"/>
							<xs:element name="EcuId" type="xs:int"/>
							<xs:element name="EcuName" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="AppHeaderInfo">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="HeaderAddress">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="0x[0-9A-Fa-f]+|[0-9]+"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="ModuleId">
								<xs:simpleType>
									<xs:restriction base="xs:int">
										<xs:enumeration value="1"/>
										<xs:enumeration value="21"/>
										<xs:enumeration value="31"/>
										<xs:enumeration value="41"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="BCID">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="0x[0-9A-Fa-f]+|[0-9]+"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="NBID">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="([1-9][0-9]?[0-9]?[0-9]?)?(0)?"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="DLS" type="xs:string"/>
							<xs:element name="PartNumber">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="0x[0-9A-Fa-f]+|[0-9]+"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="AsciiPartNumber" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="0x[0-9A-Fa-f]+|[0-9]+"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="Partitions">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Partition" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Region" minOccurs="0" maxOccurs="unbounded">
														<xs:complexType>
															<xs:attribute name="start">
																<xs:simpleType>
																	<xs:restriction base="xs:string">
																		<xs:pattern value="0x[0-9A-Fa-f]+|[0-9]+"/>
																	</xs:restriction>
																</xs:simpleType>
															</xs:attribute>
															<xs:attribute name="length">
																<xs:simpleType>
																	<xs:restriction base="xs:string">
																		<xs:pattern value="0x[0-9A-Fa-f]+|[0-9]+"/>
																	</xs:restriction>
																</xs:simpleType>
															</xs:attribute>
														</xs:complexType>
													</xs:element>
													<xs:element name="CalFiles" minOccurs="0" maxOccurs="unbounded">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="Image" minOccurs="0" maxOccurs="unbounded">
																	<xs:complexType>
																		<xs:simpleContent>
																			<xs:extension base="xs:string">
																				<xs:attribute name="BaseAddress">
																					<xs:simpleType>
																						<xs:restriction base="xs:string">
																							<xs:pattern value="0x[0-9A-Fa-f]+|[0-9]+"/>
																						</xs:restriction>
																					</xs:simpleType>
																				</xs:attribute>
																			</xs:extension>
																		</xs:simpleContent>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
															<xs:attribute name="NumberOfCalFiles" type="xs:int"/>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="NumberOfRegions" type="xs:int"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="NumberOfPartitions" type="xs:int"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="name" type="xs:string"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="CalHeaderInfo" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ModuleId" type="xs:int"/>
							<xs:element name="CCID">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="0x[0-9A-Fa-f]+|[0-9]+"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="DLS" type="xs:string"/>
							<xs:element name="PartNumber">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="0x[0-9A-Fa-f]+|[0-9]+"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="Name" type="xs:string"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="Name" type="xs:string"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== automotiveteamleader/Flashbootloader_RH850_GM/Demo/DemoAppl/Appl/ApplHdr_without_cal/ModGenBase.xml
<?xml version="1.0"?>
<GmProject Name="Application only, no calibration files" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="GmHeader.xsd">
	<HeaderVersion>1.00</HeaderVersion>
	<SignedHeaderInfo>
		<!-- SignerInfoDummyKey.hex uses Vector Demo/Dummy Key and Dummy Subject name "Engine" -->
		<image>SignerInfoDummyKey.hex</image>
		<!-- ECU ID 0 is a module meant for all ECUs (no restriction to single unique) -->
		<EcuId>00000000000000000000000000000000</EcuId>
		<!-- Demo/Dummy Ecu name -->
		<EcuName>DemoFbl1</EcuName>
	</SignedHeaderInfo>
	<AppHeaderInfo name="DemoAppl">
		<HeaderAddress>0x00020000</HeaderAddress>
		<!--  Do not use leading zeros here  -->
		<ModuleId>1</ModuleId>
		<!-- Bootloader Compatibility ID, always 0x8000 for first release -->
		<BCID>0x8000</BCID>
		<!-- Not before ID, always starts with 0 for first release. Do not use leading zeros here  -->
		<NBID>00</NBID>
		<!-- Design Level suffix, always starts with AA for first release -->
		<DLS>AA</DLS>
		<!-- Demo/Dummy part number, can be started with, replace with required number at some point -->
		<PartNumber>0x11111111</PartNumber>
		<!-- Optional Ascii part number - Remove comment and edit if desired to use -->
		<!-- <AsciiPartNumber>11111111</AsciiPartNumber> -->
		<!-- Number of Partitions == 0 if no cal modules are used. Need to be consistent to defined "Partition" element number that follows -->
		<Partitions NumberOfPartitions="0">
		</Partitions>
	</AppHeaderInfo>
	<!-- Add a CalHeaderInfo structure per required cal (non if not required) -->
</GmProject>

=== automotiveteamleader/Flashbootloader_RH850_GM/Demo/DemoUpdater/Appl/ApplHdr_Updater/ModGenBase.xml
<?xml version="1.0"?>
<GmProject Name="3 Partitions, each with 1 cal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="GmHeader.xsd">
	<HeaderVersion>1.00</HeaderVersion>
	<SignedHeaderInfo>
		<!-- SignerInfoDummyKey.hex uses Vector Demo/Dummy Key and Dummy Subject name "Engine" -->
		<image>SignerInfoDummyKey.hex</image>
		<!-- ECU ID 0 is a module meant for all ECUs (no restriction to single unique) -->
		<EcuId>00000000000000000000000000000000</EcuId>
		<!-- Demo/Dummy Ecu name -->
		<EcuName>DemoFbl1</EcuName>
	</SignedHeaderInfo>
	<AppHeaderInfo name="DemoUpdater">
		<HeaderAddress>0x00020000</HeaderAddress>
		<!--  Do not use leading zeros here  -->
		<ModuleId>1</ModuleId>
		<!-- Bootloader Compatibility ID, always 0x8000 for first release -->
		<BCID>0x8000</BCID>
		<!-- Not before ID, always starts with 0 for first release. Do not use leading zeros here  -->
		<NBID>0</NBID>
		<!-- Design Level suffix, always starts with AA for first release -->
		<DLS>AA</DLS>
		<!-- Demo/Dummy part number, can be started with, replace with required number at some point -->
		<PartNumber>0x11111111</PartNumber>
		<!-- Optional Ascii part number - Remove comment and edit if desired to use -->
		<!-- <AsciiPartNumber>11111111</AsciiPartNumber> -->
		<!-- Number of Partitions == 0 if no cal modules are used. Need to be consistent to defined "Partition" element number that follows -->
		<Partitions NumberOfPartitions="1">
			<!-- Number of Regions larger or equal 1, need to be consistent to defined "Region" element number that follows -->
			<Partition NumberOfRegions="1">
				<!-- Regions have to be in order (start with lowest address)! -->
				<Region start="0x38000" length="0x1C8000"/>
				<CalFiles NumberOfCalFiles="1">
					<!-- Image BaseAddress need to be within -->
					<Image BaseAddress="0x38000">DemoUpdater_cal_plain.gbf</Image>
				</CalFiles>
			</Partition>
      </Partitions>
	</AppHeaderInfo>
	<!-- Add a CalHeaderInfo structure per required cal (non if not required) -->
	<CalHeaderInfo Name="DemoUpdater_cal">
		<ModuleId>2</ModuleId>
		<!-- Calibration Compatibility ID, always 0x8000 for first release -->
		<CCID>0x8000</CCID>
		<!-- Design Level suffix, always starts with AA for first release -->
		<DLS>AA</DLS>
		<!-- Demo/Dummy part number, can be started with, replace with required number at some point -->
		<PartNumber>0x22222222</PartNumber>
		<!-- Optional Ascii part number - Remove comment and edit if desired to use -->
		<!-- <AsciiPartNumber>22222222</AsciiPartNumber> -->
	</CalHeaderInfo>
</GmProject>

=== automotiveteamleader/Flashbootloader_RH850_GM/Misc/HdrGen/_ModGenBase_2Part_3cal.xml
<?xml version="1.0"?>
<GmProject Name="2 Partitions, one with 2 cals, one with 1 cal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="GmHeader.xsd">
	<HeaderVersion>1.00</HeaderVersion>
	<SignedHeaderInfo>
		<!-- SignerInfoDummyKey.hex uses Vector Demo/Dummy Key and Dummy Subject name "Engine" -->
		<image>SignerInfoDummyKey.hex</image>
		<!-- ECU ID 0 is a module meant for all ECUs (no restriction to single unique) -->
		<EcuId>00000000000000000000000000000000</EcuId>
		<!-- Demo/Dummy Ecu name -->
		<EcuName>DemoFbl1</EcuName>
	</SignedHeaderInfo>
	<AppHeaderInfo name="DemoAppl">
		<HeaderAddress>0x0007C000</HeaderAddress>
		<!--  Do not use leading zeros here  -->
		<ModuleId>1</ModuleId>
		<!-- Bootloader Compatibility ID, always 0x8000 for first release -->
		<BCID>0x8000</BCID>
		<!-- Not before ID, always starts with 0 for first release. Do not use leading zeros here  -->
		<NBID>0</NBID>
		<!-- Design Level suffix, always starts with AA for first release -->
		<DLS>AA</DLS>
		<!-- Demo/Dummy part number, can be started with, replace with required number at some point -->
		<PartNumber>0x11111111</PartNumber>
		<!-- Optional Ascii part number - Remove comment and edit if desired to use -->
		<!-- <AsciiPartNumber>11111111</AsciiPartNumber> -->
		<!-- Number of Partitions == 0 if no cal modules are used. Need to be consistent to defined "Partition" element number that follows -->
		<Partitions NumberOfPartitions="2">
			<!-- Number of Regions larger or equal 1, need to be consistent to defined "Region" element number that follows -->
			<Partition NumberOfRegions="1">
				<!-- Regions have to be in order (start with lowest address)! -->
				<Region start="0x140000" length="0x4000"/>
				<CalFiles NumberOfCalFiles="2">
					<!-- Image BaseAddress need to be within -->
					<Image BaseAddress="0x140000">cal1_plain.gbf</Image>
					<Image BaseAddress="0x140800">cal2_plain.gbf</Image>
				</CalFiles>
			</Partition>
			<!-- Number of Regions larger or equal 1, need to be consistent to defined "Region" element number that follows -->
			<Partition NumberOfRegions="1">
				<!-- Regions have to be in order (start with lowest address)! -->
				<Region start="0x160000" length="0x4000"/>
				<CalFiles NumberOfCalFiles="1">
				<Image BaseAddress="0x160000">cal3_plain.gbf</Image>
				</CalFiles>
			</Partition>
		</Partitions>
	</AppHeaderInfo>
	<!-- Add a CalHeaderInfo structure per required cal (non if not required) -->
	<CalHeaderInfo Name="cal1">
		<ModuleId>2</ModuleId>
		<!-- Calibration Compatibility ID, always 0x8000 for first release -->
		<CCID>0x8000</CCID>
		<!-- Design Level suffix, always starts with AA for first release -->
		<DLS>AA</DLS>
		<!-- Demo/Dummy part number, can be started with, replace with required number at some point -->
		<PartNumber>0x22222222</PartNumber>
		<!-- Optional Ascii part number - Remove comment and edit if desired to use -->
		<!-- <AsciiPartNumber>22222222</AsciiPartNumber> --> 
	</CalHeaderInfo>
	<CalHeaderInfo Name="cal2">
		<ModuleId>3</ModuleId>
		<!-- Calibration Compatibility ID, always 0x8000 for first release -->
		<CCID>0x8000</CCID>
		<!-- Design Level suffix, always starts with AA for first release -->
		<DLS>AA</DLS>
		<!-- Demo/Dummy part number, can be started with, replace with required number at some point -->
		<PartNumber>22334455</PartNumber>
		<!-- Optional Ascii part number - Remove comment and edit if desired to use -->
		<!-- <AsciiPartNumber>0154CBF7</AsciiPartNumber> -->
	</CalHeaderInfo>
	<CalHeaderInfo Name="cal3">
		<ModuleId>4</ModuleId>
		<!-- Calibration Compatibility ID, always 0x8000 for first release -->
		<CCID>0x8000</CCID>
		<!-- Design Level suffix, always starts with AA for first release -->
		<DLS>AA</DLS>
		<!-- Demo/Dummy part number, can be started with, replace with required number at some point -->
		<PartNumber>0x44444444</PartNumber>
		<!-- Optional Ascii part number - Remove comment and edit if desired to use -->
		<!-- <AsciiPartNumber>44444444</AsciiPartNumber> -->
	</CalHeaderInfo>
</GmProject>
